#!/bin/bash

set -e

NAME='zorp'

lxc-create -n ${NAME} -t fedora -- -R 21

sed 's/empty/none/' "/var/lib/lxc/${NAME}/config"

lxc-start -n ${NAME}
sleep 5
lxc-attach -n ${NAME} -- <<EOD
yum -y install git libtool gcc-c++ zlib-devel openssl-devel glib2-devel make gperf python-devel py-radix pyOpenSSL python-pydns python-pip wget
pip install prctl

cd /usr/src

git clone https://github.com/balabit/libzorpll.git
cd libzorpll
git checkout 6.0.0.0
./autogen.sh
./configure --prefix=/usr
make
make install
cd ..

git clone https://github.com/balabit/zorp.git
cd zorp
git checkout 6.0.0
./autogen.sh
./configure --prefix=/usr
make
make install
cd ..

git clone https://github.com/balabit/kzorp.git
cd kzorp
git checkout 6.0.0
autoreconf -i
./configure --prefix=/usr
make
make install
cd ..

git clone https://github.com/jaksi/zorp-umatrix-ublock
cp zorp-umatrix-ublock/systemd-service/zorp.service /etc/systemd/system/
cp zorp-umatrix-ublock/systemd-service/zorp /etc/sysconfig/
cp zorp-umatrix-ublock/uProxy.py /etc/zorp/
cp zorp-umatrix-ublock/examples/* /etc/zorp/

wget -O /etc/zorp/abp.txt 'https://easylist-downloads.adblockplus.org/easylist.txt'

systemctl enable zorp
systemctl start zorp
EOD
